apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-bootcamp
  labels:
    app: kubernetes-bootcamp
spec:
  # THIS PAR HAS BEEN COMPLETED #2
  replicas: 3
  selector:
    matchLabels:
      app: kubernetes-bootcamp
  template:
    metadata:
      labels:
        app: kubernetes-bootcamp
    spec:
      containers:
      - name: kubernetes-bootcamp
        # ADD this line
        image: gcr.io/google-samples/kubernetes-bootcamp:v1
        #ports: 8080
        #- port: 80
        #  name: http
        #  targetPort: 80
        #- containerPort: 80
        # THIS PART HAS BEEN COMPLETED #1
