apiVersion: v1
kind: Service
metadata:
  name: kubernetes-bootcamp-service
spec:
  type: NodePort
  selector:
    app:
      kubernetes-bootcamp
      # HAS BEEN COMPLETED
  ports:
    - port: 8080
      # HAS BEEN COMPLETED
